### ISSUE TITLE
Invalid coroutine to resume with coro.sleep() call

### ISSUE THREAD

**Issue by hughjfchen** [pgiri/asyncoro#12]
I have a sleep within a generator function and I always get following error after expired:

> invalid coroutine xxxxxx to resume

the xxxxxx should be the coroutine id.

The generator function is as following:
`def generate_job(job, next_channel, coro=None):
    log.debug(job)
    coro.set_daemon()
    if utils.get_from_dict(job, ['schedule', 'repeated']):
        next_channel.send(job)
        while True:
            yield coro.sleep(utils.get_from_dict(job, ['schedule',
                                                       'repeated',
                                                       'interval']))
            next_channel.send(job)
`

**Comment by pgiri** [comment]
Is it possible to give full program that shows this behavior? Also, is it with current / recent version? Sometimes you get 'invalid coroutine to resume' warning when asyncoro is terminating, which is harmless. It is also possible that the warning message is not about 'generate_job' but a recipient to 'next_channel' that may have terminated. You can figure this out by printing each coroutine you create (or at least that subscribes to 'next_channel') with ``print('coroutine: %s' % coro)`` so when invalid id warning is shown you can figure out which coroutine terminated.

**Comment by hughjfchen** [comment]
Thanks for your reply. Yes,I'm also thinking that must be caused by the coroutine had been terminated. So I checked all my generator function and found some of them are not infinite loop, so it must be terminated after once run. Having these function fixed, the problem gone. I'll close this issue and thanks again.
