### ISSUE TITLE
When is an coroutine closed? How to determine the state of an coroutine?

### ISSUE THREAD

**Issue by hughjfchen** [pgiri/asyncoro#13]
My program often gets "invalid coroutine xxxx to resume" messages during running. I want to know how to determine the state of an coroutine and when it'll be closed.

**Comment by pgiri** [comment]
You can use `coro.is_alive()` but this shouldn't be required usually. A coroutine terminates similar to how a thread terminates when its function terminates - when control reaches end or if coroutine executes `raise StopIteration` (which is analogous to `return` in functions of threads) or if coroutine throws an exception that is not caught. Running  with debug logging level may help in some cases.

**Comment by hughjfchen** [comment]
Thanks for your clarification.
