### ISSUE TITLE
Running simple async process in the background

### ISSUE THREAD

**Issue by renderit** [pgiri/asyncoro#14]
Great work here! I'm trying to use this on a raspberry pi, which collects bunch of points and writes to a influx database.. Since the writing is in bulk, because of network IO, it stops the program when doing the 'post request' to the database, :(  hence I was trying to use asyncoro library..As I understand the `some_long_func()` is suppose to return a generator. I'm confused with this part, since I ONLY want to make the processing work in the background while not stopping the main event loop.. What should I return in that case? How can I do this? 

```
def some_long_func(coro=None):
    ""this function does a long POST request using some custom library""
    #yield coro.sleep(0.1)
    TimeSeriesHelper(send_json_to_server) # class for doing the work of POST
    print 'final done'

def main_func():
    asyncoro.Coro(some_long_func)
    for i in range(20):
        print i
        time.sleep(0.5)
main_func()
```

**Comment by pgiri** [comment]
In your case `some_long_func` should be a generator function that `yield`s whenever calling I/O function, `coro.sleep` etc. For example, posting request can be done with `AsyncDBCursor` call and while waiting for it to complete, you can process other I/O with coroutines. However, `time.sleep` shouldn't be used in the program - this blocks entire asyncoro framework and no coroutines would be executing during that sleep. Instead, `coro.sleep` must be used (only in coroutines, and not in `main_func` as above).

Note that if you want to run CPU bound coroutines, you may want to look at `discoro` to distribute computations among cores / nodes.

Essentially asyncoro is like an operating system scheduler that executes coroutines as kernel executes processes, scheduler gets control when `yield` is used ala "sysctl" in Unix.  etc., all done with API similar to threading module in Python. In fact, I am thinking of renaming asyncoro project to better reflect this, which may help in understanding it better.

**Comment by renderit** [comment]
Great thanks for that info! I guess I'll stick with `threading` module for now..
