### ISSUE TITLE
PyPI Installation

### ISSUE THREAD

**Issue by queertypes** [pgiri/asyncoro#2]
Needs:

- setup.py (most of the info is already in the asyncoro.py files)
    * classifiers
    * author
    * email
    * version
    * license
    * project URL
- MANIFEST.in
- a means to determine from setup.py which asyncoro to install (2 or 3)

I'll be glad to take this on if interest in this issue is demonstrated.

**Comment by pgiri** [comment]
This issue was resolved quite a while ago.
