### ISSUE TITLE
AttributeError: '_AsyncNotifier' object has no attribute '_poller_name' on windows with pywin32

### ISSUE THREAD

**Issue by wangeek** [pgiri/asyncoro#5]
When I tried to run dispynode.py from dispy pacakge on win8 x86 with python 2.7.9 and pywin32 installed, I got this:

Traceback (most recent call last):
  File ".\dispynode.py", line 1691, in <module>
    _dispy_node = _DispyNode(**_dispy_config)
  File ".\dispynode.py", line 247, in __init__
    self.asyncoro = AsynCoro()
  File "D:\Python27\lib\site-packages\asyncoro\__init__.py", line 78, in __call__
    cls.__instance = super(MetaSingleton, cls).__call__(*args, **kwargs)
  File "D:\Python27\lib\site-packages\asyncoro\__init__.py", line 3109, in __init__
    __version__, self._notifier._poller_name)
AttributeError: '_AsyncNotifier' object has no attribute '_poller_name'

__version__ = "3.6.15"
Remove lines 3108 and 3109,  works fine.

**Comment by pgiri** [comment]
A fix for this is committed in ba646c5acb98fdb5b84f4ba20ca39372a4f44969; I haven't tested it, though.

**Comment by pgiri** [comment]
I tested it and released asyncoro-3.6.16 with the fix, as this issue affects Windows users of both asyncoro and dispy. Thanks for reporting the issue.

**Comment by pgiri** [comment]
This issue has been fixed as noted above.
